name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Creating .env
        run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env

      - name: Install dependencies
        run: go get -v ./...

      - name: Test
        run: go test -v .